-- Add conflict_original_id column to store the scanner-generated composite ID
-- This allows us to track conflicts using the scanner's ID while maintaining UUID primary keys

ALTER TABLE public.conflicts 
ADD COLUMN IF NOT EXISTS conflict_original_id TEXT UNIQUE;

-- Add index for efficient lookups by original ID
CREATE INDEX IF NOT EXISTS idx_conflicts_original_id ON public.conflicts(conflict_original_id);

-- Add comment
COMMENT ON COLUMN public.conflicts.conflict_original_id IS 'Original composite ID generated by conflict scanner (e.g., teacher_overlap_uuid_uuid)';

-- Verify the column was added
SELECT column_name, data_type, is_nullable 
FROM information_schema.columns 
WHERE table_name = 'conflicts' 
AND table_schema = 'public' 
AND column_name = 'conflict_original_id';
